[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server-security = "0.1.1"
tokio = "1.18.2"

[[bin]]
name = "proxy"
path = "main.rs"
